[tool.poetry]
name = "open-interpreter"
packages = [
    {include = "interpreter"},
    {include = "cli"}
]
version = "0.0.241"
description = "Ask GPT-4 to run code locally."
authors = ["Killian Lucas <killian@drinkwater.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
openai = "^0.27.8"
rich = "^13.4.2"
tiktoken = "^0.4.0"
ipython = "^8.14.0"
astor = "^0.8.1"
git-python = "^1.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
interpreter = "cli:cli"