[tool.poetry]
name = "open-interpreter"
packages = [
    {include = "interpreter"}
]
version = "0.0.21"
description = "Ask GPT-4 to run code locally"
authors = ["Killian Lucas <killian@drinkwater.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
openai = "^0.27.8"
rich = "^13.4.2"
tiktoken = "^0.4.0"
astunparse = "^1.6.3"
ipython = "^8.14.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"